-- MySQL Script generated by MySQL Workbench
-- Sat Nov 30 15:28:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CONFERENCE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CONFERENCE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CONFERENCE` DEFAULT CHARACTER SET utf8 ;
USE `CONFERENCE` ;

-- -----------------------------------------------------
-- Table `CONFERENCE`.`ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONFERENCE`.`ROLE` (
  `id_ROLE` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `vah` INT NOT NULL,
  PRIMARY KEY (`id_ROLE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONFERENCE`.`UZIVATEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONFERENCE`.`UZIVATEL` (
  `id_UZIVATEL` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `heslo` VARCHAR(40) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `ROLE_id_ROLE` INT NOT NULL,
  PRIMARY KEY (`id_UZIVATEL`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_UZIVATEL_ROLE1_idx` (`ROLE_id_ROLE` ASC) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) ,
  CONSTRAINT `fk_UZIVATEL_ROLE1`
    FOREIGN KEY (`ROLE_id_ROLE`)
    REFERENCES `CONFERENCE`.`ROLE` (`id_ROLE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONFERENCE`.`PRISPEVEK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONFERENCE`.`PRISPEVEK` (
  `id_PRISPEVEK` INT NOT NULL AUTO_INCREMENT,
  `obsah` LONGTEXT NOT NULL,
  `nazev` VARCHAR(50) NOT NULL,
  `rozhodnuti` TINYINT NULL DEFAULT 0,
  `nazev_souboru` VARCHAR(45) NULL,
  `UZIVATEL_id_UZIVATEL` BIGINT NOT NULL,
  PRIMARY KEY (`id_PRISPEVEK`),
  INDEX `fk_PRISPEVEK_UZIVATEL1_idx` (`UZIVATEL_id_UZIVATEL` ASC) ,
  CONSTRAINT `fk_PRISPEVEK_UZIVATEL1`
    FOREIGN KEY (`UZIVATEL_id_UZIVATEL`)
    REFERENCES `CONFERENCE`.`UZIVATEL` (`id_UZIVATEL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONFERENCE`.`RECENZE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONFERENCE`.`RECENZE` (
  `id_RECENZE` INT NOT NULL AUTO_INCREMENT,
  `originalita` TINYINT(5) NOT NULL,
  `tema` TINYINT(5) NOT NULL,
  `technicka_kvalita` TINYINT(5) NOT NULL,
  `jazykova_kvalita` TINYINT(5) NOT NULL,
  `doporuceni` TINYINT(5) NOT NULL,
  `poznamky` LONGTEXT NULL,
  `id_UZIVATEL` BIGINT NOT NULL,
  `PRISPEVEK_id_PRISPEVEK` INT NOT NULL,
  PRIMARY KEY (`id_RECENZE`),
  INDEX `fk_RECENZE_UZIVATEL1_idx` (`id_UZIVATEL` ASC) ,
  INDEX `fk_RECENZE_PRISPEVEK1_idx` (`PRISPEVEK_id_PRISPEVEK` ASC) ,
  CONSTRAINT `fk_RECENZE_UZIVATEL1`
    FOREIGN KEY (`id_UZIVATEL`)
    REFERENCES `CONFERENCE`.`UZIVATEL` (`id_UZIVATEL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECENZE_PRISPEVEK1`
    FOREIGN KEY (`PRISPEVEK_id_PRISPEVEK`)
    REFERENCES `CONFERENCE`.`PRISPEVEK` (`id_PRISPEVEK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
